---
- name: Selecionando o Instance Group
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:

    - name: Definindo o instance group de acordo com o datacenter
      ansible.builtin.include_role:
        name: ig