- name: Mapear datacenter para instance group ID
  ansible.builtin.set_fact:
    ig_map:
      Campinas: 3
      Lapa: 4
      Mackenzie: 5

- name: Mapear Credenciais
  ansible.builtin.set_fact:
    cd_map:
      Campinas: 85
      Lapa: 79
      Mackenzie: 35


- name: Buscar lista de templates do workflow
  ansible.builtin.set_fact:
    template_ids:
      - 861  # meu-job-template-de-sh


- name: Atualizar instance_group de cada template
  ansible.builtin.include_tasks: set_instance_group.yaml
  loop: "{{ template_ids }}"
  loop_control:
    loop_var: template_id

- name: Atualizar credentials de cada template
  ansible.builtin.include_tasks: set_credentials.yaml
  loop: "{{ cd_map }}"
  loop_control:
    loop_var: cd_id