- name: "Buscar instance groups atualmente associados ao template {{ template_id }}"
  ansible.builtin.uri:
    url: "https://aap.claro.com.br/api/controller/v2/job_templates/{{ template_id }}/instance_groups/"
    method: GET
    headers:
      Authorization: "Bearer {{ aap_api_token }}"
    validate_certs: false
  register: current_igs
  no_log: true

- name: "Desassociar instance groups divergentes do template {{ template_id }}"
  ansible.builtin.uri:
    url: "https://aap.claro.com.br/api/controller/v2/job_templates/{{ template_id }}/instance_groups/"
    method: POST
    headers:
      Authorization: "Bearer {{ aap_api_token }}"
    body_format: json
    body:
      id: "{{ existing_ig.id }}"
      disassociate: true
    status_code: [204]
    validate_certs: false
  loop: "{{ current_igs.json.results }}"
  loop_control:
    loop_var: existing_ig
  when: existing_ig.id != ig_map[datacenter_name]
  no_log: true

- name: "Associar instance group correto ({{ ig_map[datacenter_name] }}) ao template {{ template_id }}"
  ansible.builtin.uri:
    url: "https://aap.claro.com.br/api/controller/v2/job_templates/{{ template_id }}/instance_groups/"
    method: POST
    headers:
      Authorization: "Bearer {{ aap_api_token }}"
    body_format: json
    body:
      id: "{{ ig_map[datacenter_name] }}"
    status_code: [204]
    validate_certs: false
  when: ig_map[datacenter_name] not in (current_igs.json.results | map(attribute='id') | list)
  no_log: true