---
###############################################
# VARIAVEIS
###############################################

- name: Extrair nome do owner
  ansible.builtin.set_fact:
    owner_home: "{{ filesystem.split('/')[-1] | lower }}"

- name: Resolver email do owner
  ansible.builtin.set_fact:
    email_destino: >-
      {{
        dono_home[owner_home]
        | default(email_default)
      }}

###############################################
# USO DO DIRETORIO
###############################################

- name: Obter utilizacao do filesystem
  ansible.builtin.raw: |
    df -hP {{ filesystem }} | awk 'NR==2 {print $5}'
  register: uso_fs

###############################################
# MAIORES DIRETORIOS
###############################################

- name: Levantar maiores diretorios
  ansible.builtin.raw: |
    du -xsm {{ filesystem }}/* 2>/dev/null \
    | sort -nr \
    | head -20
  register: top_dirs

###############################################
# MAIORES ARQUIVOS
###############################################

- name: Levantar maiores arquivos
  ansible.builtin.raw: |
    find {{ filesystem }} -type f \
    -exec ls -lh {} \; 2>/dev/null \
    | sort -k5 -hr \
    | head -20
  register: top_files

###############################################
# EMAIL
###############################################

- name: Enviar email
  community.general.mail:
    host: vip_smtp.claro.com.br
    port: 25
    from: coeeaiops@claro.com.br
    to: "{{ email_destino }}"
    subject: "[ALERTA] Diretorio cheio - {{ filesystem }} - {{ inventory_hostname }}"
    subtype: plain
    body: |

      Prezados,

      Foi identificado consumo acima do limite configurado.

      Host:
      {{ inventory_hostname }}

      Diretorio:
      {{ filesystem }}

      Utilizacao:
      {{ uso_fs.stdout | trim }}

      ==================================================
      TOP DIRETORIOS
      ==================================================

      {{ top_dirs.stdout }}

      ==================================================
      TOP ARQUIVOS
      ==================================================

      {{ top_files.stdout }}

      ==================================================

      Favor avaliar a necessidade de limpeza.

      Email enviado automaticamente pelo AIOps.

###############################################
# SPLUNK
###############################################

- name: Reportar resultado
  ansible.builtin.set_stats:
    data:
      resultado_do_primeiro_job: "{{ tower_job_id | default('N/A') }}"
      tipo_selfhealing: "disco"
      nome_servico: "{{ filesystem }}"
      metrica_antes: "{{ uso_fs.stdout | trim }}"
      metrica_depois: "EMAIL_ENVIADO"
      metrica_esperada: "<=90"